export const ASYNC_STORAGE_ACCESS_TOKEN = '@ASYNC_STORAGE_ACCESS_TOKEN'
export const ASYNC_STORAGE_REFRESH_TOKEN = '@ASYNC_STORAGE_REFRESH_TOKEN'
export const ASYNC_STORAGE_CURRENT_USER = '@ASYNC_STORAGE_CURRENT_USER'
